
pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps { checkout scm }
    }
    stage('Install') {
      steps {
        dir('app') {
          sh 'npm install'
        }
      }
    }
    stage('Test') {
      steps {
        dir('app') {
          sh 'npm test'
        }
      }
    }
    stage('Build Docker') {
      steps {
        sh 'docker build -t weather-dashboard:latest .'
      }
    }
  }
}
